name = "hurricanehub"
main = "./dist/server/entry.mjs"
compatibility_date = "2026-07-28"
compatibility_flags = ["nodejs_compat"]
no_bundle = true
workers_dev = true
preview_urls = true

routes = [
  { pattern = "hurricanetracker.cc/*", zone_name = "hurricanetracker.cc" },
  { pattern = "www.hurricanetracker.cc/*", zone_name = "hurricanetracker.cc" }
]

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"] }
]

[assets]
binding = "HURRICANEHUB_STATIC"
directory = "./dist/client"

[[kv_namespaces]]
binding = "SESSION"

[[kv_namespaces]]
binding = "HURRICANEHUB_CACHE"
id = "0d55cd1eaac145b49e6367ff4c89397d"
